config/routes.rb
Tweetmark::Application.routes.draw do
  get "new/create"

  get "new/destroy"

  get "hashtags/new"

  get "hashtags/create"

  get "hashtags/edit"

  get "tweets/new"

  get "tweets/create"

  get "tweets/update"

  get "tweets/edit"

  get "tweets/destroy"

  root :to => "users#index"

  resources :users
  match "/auth/twitter/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout

end

app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
  attr_accessible :label
  has_many :tweets, :through => :tweethashes
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :user
    has_many :hashtags, :through => :tweethashes
    attr_accessible :text
  @@consumer_key = "Wko8AqUdjesPW5aK4MTxQ"
  @@consumer_secret = "FkgvnrfuxhItAk5YUhv9ZGUIJVmJT3gkLV6MYX8"

  def self.get_user_tweets
    @user = User.first
    @client = TwitterOAuth::Client.new(
      # :consumer_key => ENV["TWITTER_KEY"],
      #   :consumer_secret => ENV["TWITTER_SECRET"],
      :consumer_key => @@consumer_key,
      :consumer_secret => @@consumer_secret,
      :token => @user.auth_token,
      :secret => @user.auth_secret
      )
      @client.user_timeline(
      :screen_name => @user.twitter_name,
      :count => 6,
      :include_entities => true
      )
  end

  def self.find_by_tag

  end

end
#
# class Tweet < ActiveRecord::Base
#   belongs_to :user
#   has_many :hashtags, :through => :tweethashes
#   attr_accessible :text
#
#
#
#   def self.get_user_tweets
#     user = User.first
#     client = TwitterOAuth::Client.new(
#         :consumer_key => "6KmZfBk2kSeqA8lgrcQhA",
#         :consumer_secret => "aWdvrK39iyt6ZImJjT4ViiqT03ejPs5uvl15SdBRqCs",
#         :token => user.auth_token,
#         :secret => user.auth_secret
#     )
#     return client
#   end
#
#   request_token = client.request_token(:oauth_callback => oauth_confirm_url)
#   #:oauth_callback required for web apps, since oauth gem by default force PIN-based flow
#   #( see http://groups.google.com/group/twitter-development-talk/browse_thread/thread/472500cfe9e7cdb9/848f834227d3e64d )
#
#
#   request_token.authorize_url
#   => http://twitter.com/oauth/authorize?oauth_token=TOKEN
# end

app/models/url.rb
class Url < ActiveRecord::Base
  attr_accessible :website
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :auth_secret, :auth_token, :name, :provider, :twitter_name, :uid, :image_url

  has_many :tweets
  has_many :hashtags, :through => :tweets

  def self.create_with_omniauth(auth)
      create! do |user|
        user.provider = auth["provider"]
        user.uid = auth["uid"]
        user.name = auth["info"]["name"]
        user.twitter_name = auth["info"]["nickname"]
        user.image_url = auth["info"]["image"]
        user.auth_token = auth["credentials"]["token"]
        user.auth_secret = auth["credentials"]["secret"]
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  def new
    @hashtag = Hashtag.new
  end

  def create
  end

  def edit
  end
end

app/controllers/new_controller.rb
class NewController < ApplicationController
  def create
  end

  def destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
      auth = request.env["omniauth.auth"]
      p '#' * 100
      p auth.to_json
      user = User.find_by_uid(auth["uid"]) || User.create_from_omniauth(auth)
      session[:user_id] = user.id
      redirect_to user_path(user), notice: "Signed in!"
    end

    def destroy
      session[:user_id] = nil
      redirect_to user_path(User.first), notice: "Signed out!"
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def new
    @tweet = Tweet.new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @tweets = Tweet.get_user_tweets
  end

  def new
    @user = User.new
  end

  def create

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hashtags/create.html.erb
<h1>Hashtags#create</h1>
<p>Find me in app/views/hashtags/create.html.erb</p>

app/views/hashtags/edit.html.erb
<h1>Hashtags#edit</h1>
<p>Find me in app/views/hashtags/edit.html.erb</p>

app/views/hashtags/new.html.erb
<h1>Hashtags#new</h1>
<p>Find me in app/views/hashtags/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />

  <!-- Uncomment to make IE8 render like IE7 -->
  <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "the tweetbox" %></title>

  <!-- Included CSS Files -->
  <%= stylesheet_link_tag    "application" %>

  <!-- Included JS Files  -->
  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/new/create.html.erb
<h1>New#create</h1>
<p>Find me in app/views/new/create.html.erb</p>

app/views/new/destroy.html.erb
<h1>New#destroy</h1>
<p>Find me in app/views/new/destroy.html.erb</p>

app/views/tweets/create.html.erb
<h1>Tweets#create</h1>
<p>Find me in app/views/tweets/create.html.erb</p>

<%= get_user_tweets %>

app/views/tweets/destroy.html.erb
<h1>Tweets#destroy</h1>
<p>Find me in app/views/tweets/destroy.html.erb</p>

app/views/tweets/edit.html.erb
<h1>Tweets#edit</h1>
<p>Find me in app/views/tweets/edit.html.erb</p>

app/views/tweets/new.html.erb
<h1>Tweets#new</h1>
<p>Find me in app/views/tweets/new.html.erb</p>

app/views/tweets/update.html.erb
<h1>Tweets#update</h1>
<p>Find me in app/views/tweets/update.html.erb</p>

app/views/users/new.html.haml
.row
  .three.columns
    = image_tag "tweetboxlogo.png"
  .five.columns.end
    %h1 the tweetbox
    %h4 tweet outside the box

#container
  .box
    .label
      = "#SF"
    .photos
      = image_tag "http://a0.twimg.com/profile_images/1372503816/image_normal.jpg"
      = image_tag "http://a0.twimg.com/profile_images/1206777536/20567_243449561736_500561736_3147444_7231668_n_normal.jpg"
      = image_tag "http://a0.twimg.com/profile_images/1606354121/natashatherobot-eightbit_normal"
      = image_tag "http://a0.twimg.com/profile_images/1606354121/natashatherobot-eightbit_normal"

  .box
    .label
      = "#DBC"
    .photos
      = image_tag "http://a0.twimg.com/sticky/default_profile_images/default_profile_1_normal.png"
      = image_tag "http://a0.twimg.com/profile_images/1606354121/natashatherobot-eightbit_normal"

  .box
    .label
      = "#FOOD"
    .photos
      = image_tag "http://a0.twimg.com/profile_images/1372503816/image_normal.jpg"
      = image_tag "http://a0.twimg.com/profile_images/1206777536/20567_243449561736_500561736_3147444_7231668_n_normal.jpg"
  .box
    .label
      = "#SF"
    .photos
      = image_tag "http://a0.twimg.com/profile_images/1372503816/image_normal.jpg"
      = image_tag "http://a0.twimg.com/profile_images/1206777536/20567_243449561736_500561736_3147444_7231668_n_normal.jpg"
      = image_tag "http://a0.twimg.com/profile_images/1606354121/natashatherobot-eightbit_normal"
      = image_tag "http://a0.twimg.com/profile_images/1606354121/natashatherobot-eightbit_normal"

  .box
    .label
      = "#DBC"
    .photos
      = image_tag "http://a0.twimg.com/sticky/default_profile_images/default_profile_1_normal.png"
      = image_tag "http://a0.twimg.com/profile_images/1606354121/natashatherobot-eightbit_normal"

  .box
    .label
      = "#FOOD"
    .photos
      = image_tag "http://a0.twimg.com/profile_images/1372503816/image_normal.jpg"
      = image_tag "http://a0.twimg.com/profile_images/1206777536/20567_243449561736_500561736_3147444_7231668_n_normal.jpg"
  .box
    .label
      = "#NATASHA"
    .photos
      = image_tag "http://a0.twimg.com/profile_images/1372503816/image_normal.jpg"
      = image_tag "http://a0.twimg.com/profile_images/1206777536/20567_243449561736_500561736_3147444_7231668_n_normal.jpg"
      = image_tag "http://a0.twimg.com/profile_images/1606354121/natashatherobot-eightbit_normal"
      = image_tag "http://a0.twimg.com/profile_images/1606354121/natashatherobot-eightbit_normal"
      = image_tag "http://a0.twimg.com/profile_images/1372503816/image_normal.jpg"
      = image_tag "http://a0.twimg.com/profile_images/1206777536/20567_243449561736_500561736_3147444_7231668_n_normal.jpg"
      = image_tag "http://a0.twimg.com/profile_images/1606354121/natashatherobot-eightbit_normal"
      = image_tag "http://a0.twimg.com/profile_images/1606354121/natashatherobot-eightbit_normal"

  .box
    .label
      = "#DAVID"
    .photos
      = image_tag "http://a0.twimg.com/sticky/default_profile_images/default_profile_1_normal.png"
      = image_tag "http://a0.twimg.com/profile_images/1606354121/natashatherobot-eightbit_normal"

  .box
    .label
      = "#KENDRA"
    .photos
      = image_tag "http://a0.twimg.com/profile_images/1372503816/image_normal.jpg"
      = image_tag "http://a0.twimg.com/profile_images/1206777536/20567_243449561736_500561736_3147444_7231668_n_normal.jpg"
      = image_tag "http://a0.twimg.com/profile_images/1206777536/20567_243449561736_500561736_3147444_7231668_n_normal.jpg"
      = image_tag "http://a0.twimg.com/profile_images/1606354121/natashatherobot-eightbit_normal"
  .box
    .label
      = "#JACKIE"
    .photos
      = image_tag "http://a0.twimg.com/profile_images/1372503816/image_normal.jpg"
      = image_tag "http://a0.twimg.com/profile_images/1206777536/20567_243449561736_500561736_3147444_7231668_n_normal.jpg"
      = image_tag "http://a0.twimg.com/profile_images/1606354121/natashatherobot-eightbit_normal"
      = image_tag "http://a0.twimg.com/profile_images/1606354121/natashatherobot-eightbit_normal"

  .box
    .label
      = "#BANANADEBT"
    .photos
      = image_tag "http://a0.twimg.com/sticky/default_profile_images/default_profile_1_normal.png"
      = image_tag "http://a0.twimg.com/profile_images/1606354121/natashatherobot-eightbit_normal"

  .box
    .label
      = "#WATERWATEREVERYWHERE"
    .photos
      = image_tag "http://a0.twimg.com/profile_images/1372503816/image_normal.jpg"
      = image_tag "http://a0.twimg.com/profile_images/1206777536/20567_243449561736_500561736_3147444_7231668_n_normal.jpg"

app/views/users/show.html.haml
- if current_user
  Welcome #{current_user.name}!
  = image_tag current_user.image_url
  = link_to "Sign Out", signout_path
- else
  = link_to "Sign in with Twitter", "/auth/twitter"

- @tweets.each do |tweet|
  -# = tweet.inspect
  = tweet["text"]